/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.svb.aws.codedeploy.plugin

import com.svb.aws.codedeploy.plugin.CodedeployExtension
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class AwsCodedeployPlugin: Plugin<Project> {
    override fun apply(project: Project) {

        val extension = project.extensions.create(
                "codedeploy",
                CodedeployExtension::class.java,
                project)

        // Register a task
        project.tasks.register("deploy") { task ->
            task.doLast {
                println("Hello from plugin 'com.svb.aws.codedeploy.plugin.deploy'")
            }
        }
    }
}
