/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.svb.aws.codedeploy.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.svb.aws.codedeploy.plugin.greeting' plugin.
 */
class AwsCodedeployPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.svb.aws.codedeploy.plugin.deploy")

        // Verify the result
        assertNotNull(project.tasks.findByName("deploy"))
    }
}
