/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.svb.aws.codedeploy.plugin

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.svb.aws.codedeploy.plugin.greeting' plugin.
 */
class AwsCodedeployPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('com.svb.aws.codedeploy.plugin.deploy')
            }
            codedeploy {
                application = "test app"
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("deploy")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'com.svb.aws.codedeploy.plugin.deploy'"))
    }
}
